# Generated by Django 5.2.7 on 2025-10-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='time',
        ),
    ]
